---
# Secret for user-service
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: online-event-booking-hamza-omer
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET_KEY: bXlzZWNyZXRrZXk=
  POSTGRES_DB: dXNlcl9kYg==
