---
# Secret for event-service
apiVersion: v1
kind: Secret
metadata:
  name: event-service-secret
  namespace: online-event-booking-hamza-omer
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: YWRtaW5wYXNzd29yZA==
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5wYXNzd29yZA==
  MONGO_INITDB_DATABASE: ZXZlbnRfZGI=
