---
# Secret for booking-service (PostgreSQL credentials)
apiVersion: v1
kind: Secret
metadata:
  name: booking-service-secret
  namespace: online-event-booking-hamza-omer
type: Opaque
data:
  POSTGRES_USER: Ym9va2luZ191c2Vy
  POSTGRES_PASSWORD: Ym9va2luZ19wYXNzd29yZA==
  POSTGRES_DB: Ym9va2luZ19kYg==               # booking_db
  JWT_SECRET_KEY: bXlzZWNyZXRrZXk=
