---
# Secret for notification-service
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: online-event-booking-hamza-omer
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: YWRtaW5wYXNzd29yZA==
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5wYXNzd29yZA==
  MONGO_INITDB_DATABASE: bm90aWZpY2F0aW9uX2Ri
